# Generated by Django 4.0.6 on 2026-01-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0004_merge_0003_auto_20210726_1109_0003_auto_20210727_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSendSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.order')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.orderproduct')),
            ],
        ),
    ]
